name: Deploy to Cloudflare Pages

on:
    workflow_dispatch:
     inputs:
      environment:
        description: "Select Environment"
        type: environment
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
      
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build 

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: astro-cloudflare
        directory: dist
